### ISSUE TITLE
blocks.registerBlockType addFilter doesn't work within init hook

### ISSUE THREAD

**Issue by alexander-kozhukhovski** [moderntribe/square-one#1026]
**Issue:**

It was noticed that the `registerBlockType` filter doesn't run if it is inside `ready( init );` call.

The following example will not work as expected if we put the filter within `init` at `wp-content/themes/core/assets/js/src/admin/editor/hooks.js` ([here](https://github.com/moderntribe/square-one/blob/dd9ca0ece9e77952c150c7a1b338c02c9f89e0d5/wp-content/themes/core/assets/js/src/admin/editor/hooks.js#L23)):

`addFilter( 'blocks.registerBlockType', 'tribe/filter-alignment', setAlignmentSupports );` 

**Potential Solution:**
We can create a separate file with all the `registerBlockType` filters required and hook it directly before the [ready( init )](https://github.com/moderntribe/square-one/blob/dd9ca0ece9e77952c150c7a1b338c02c9f89e0d5/wp-content/themes/core/assets/js/src/admin/core/ready.js#L63) call

**Comment by ChrisMKindred** [comment]
@alexander-kozhukhovski Can you provide more details on this issue? A link to the call would be nice for troubleshooting and a potential solution if you have one.

**Comment by alexander-kozhukhovski** [comment]
> @alexander-kozhukhovski Can you provide more details on this issue? A link to the call would be nice for troubleshooting and a potential solution if you have one.

Description and possible solution added.

**Comment by alexander-kozhukhovski** [comment]
Resolved with [PR-1036](https://github.com/moderntribe/square-one/pull/1036)

**Comment by alexander-kozhukhovski** [comment]
Resolved with https://github.com/moderntribe/square-one/pull/1036
