### ISSUE TITLE
Add ability to add custom user roles

### ISSUE THREAD

**Issue by rwrobe** [moderntribe/square-one#330]
The Core plugin contains a framework for easily adding object meta, post types, taxonomies, but lacks a standard way to add user roles. It would be nice to have a similar config for user roles.

@jbrinley Mentioned that he used something he liked for Steelcase

**Comment by nickpelton** [comment]
Closing since this functionality has been proposed in Tribe libs 

See https://github.com/moderntribe/tribe-libs/pull/31
