### ISSUE TITLE
Glomar Default Text can be Confusing for Clients

### ISSUE THREAD

**Issue by binarygary** [moderntribe/square-one#345]
Goodness this is a stodgy-old-professor complaint but hear me out.

I recently had a situation where a new client stake holder needed to be brought up to speed in a hurry and I passed them a link on staging. Almost immediately came the response of "It's broken, no matter what I do I get some kind of not-found page". Not found sounds kinda like a 404 situation. And in this case, that's exactly what it was. I had not adequately prepped this customer to access staging and as a result his first exposure to tribe was:

`We can neither confirm nor deny the existence or nonexistence of records responsive to your request. The fact of the existence or nonexistence of requested records is currently and properly classified and is intelligence sources and methods information that is protected from disclosure.`

I'd like to propose we drop the browser facing glomar text and back story and replace with a more general description of why this is 404ing. I think the radiolab episode (and subsequent 1.5 hour wikipedia rabbit hole :joy:) are a fun part of onboarding for devs. I'd propose we preserve the plugin naming and "archive" the radiolab link and text in the codebase.

**Comment by ryanurban** [comment]
Agreed, I'll ticket this in the SQ1 project. Thanks Gary!
