### ISSUE TITLE
Codeception doesn't populate DB

### ISSUE THREAD

**Issue by rwrobe** [moderntribe/square-one#358]
After following instructions for the new project setup, specifically getting the testing suite running, the following error appears:
```
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
Codeception PHP Testing Framework v3.0.3
Powered by PHPUnit 8.3.3 by Sebastian Bergmann and contributors.
Running with seed: 
WPLoader could not correctly load WordPress.
If you do not see any other output beside this, probably a call to `die` or `exit` might have been made while loading WordPress files.
There are a number of reasons why this might happen and the most common is an empty, incomplete or incoherent database status.
E.g. you are trying to bootstrap WordPress as multisite on a database that does not contain multisite tables.
Run the same test command again activating debug (-vvv) to run a WordPress status check.
It looks like, alongside the WPLoader module, you are using the WPDb one.
Since the `WPLoader::loadOnly` parameter is set to `true` the WPLoader module will not try to populate the database.
The database should be populated from a dump using the WPDb modules.
Make sure the SQL dump you're trying to use is not empty and correct for the kind of installation you are trying to test.
Make also sure that, in the suite configuration file, in the `modules` section, the WPDb modules comes before the WPLoader one.
If you are, instead, trying to run integration tests you do not probably need the WPDb module or should set the `populate` and `cleanup` arguments to `false` and set the `WPLoader::loadOnly` parameter to `false` to let the WPLoader module populate the database for you.
Find out more about this at https://wpbrowser.wptestkit.dev/summary/modules/wploader#wploader-to-only-bootstrap-wordpress
```

## Steps to Reproduce

Create a new [1] project with a name other than `square1` by following the getting started guide for a new project. Configure the `.env` and `tests-config.php` files. Run `npm run codecept:test` from the project root.

**Comment by Luc45** [comment]
Does the test database exist? Eg: `projectid_tests`

The way integration and acceptance tests handle database in tests are completely different, so it might be a good thing to try with both suites isolated

**Comment by rwrobe** [comment]
The test database does exist-- the root of the problem turned out to be that `dev/tests/tests/_data/dump.sql` imported to the DB with the site URL set to `http://square1.tribe`. The attempt to redirect killed the tests. I'll add this note to the PR I'm making.

**Comment by defunctl** [comment]
The `dump.sql` should be updated for each site you're testing though.

**Comment by rwrobe** [comment]
We can add this to the README for the tests and comment out the populator?

**Comment by defunctl** [comment]
> We can add this to the README for the tests and comment out the populator?

Does the replace URL functionality not work with the populator or something, just wondering why it's being disabled in the first place.

**Comment by rwrobe** [comment]
Doesn't actually seem to autopopulate without a DB dump anyway. May just need to update the documentation.

**Comment by nickpelton** [comment]
Is this relevant with the the forthcoming test framework? Latest test framework is functional and integrated with GHA. https://github.com/moderntribe/square-one/tree/epic/fidgety-feet

**Comment by ryanurban** [comment]
@rwrobe this still an issue?
