### ISSUE TITLE
TravisCI setup needs better env support

### ISSUE THREAD

**Issue by rwrobe** [moderntribe/square-one#362]
TravisCI fails right now on builds because of issues with the tr1b0t oAuth token and the missing `.env` file in the Composer install step. We need to allow for env vars set in TravisCI to be available to Docker Compose.

**Comment by defunctl** [comment]
I've begun to address a bunch of this in https://github.com/moderntribe/square-one/pull/351

**Comment by nickpelton** [comment]
Moving to Github Actions for CI.
