### ISSUE TITLE
Documentations and video links don't work

### ISSUE THREAD

**Issue by M4N0JKUM4R** [moderntribe/square-one#652]
Hey there,

I would love to have a look into this but can you fix the documentation and video links like these: 

https://github.com/moderntribe/square-one/blob/main/docs/frontend/README.md
https://vimeo.com/194057171

**Comment by ryanurban** [comment]
Hi, thanks for noting this! We definitely need to spend some more time doing an update and overhaul on the documentation after performing a pretty major update to SQ1.
