### ISSUE TITLE
Docs Still Refer to Twig in Templating.md

### ISSUE THREAD

**Issue by tarecord** [moderntribe/square-one#697]
[docs/concepts/templating.md](https://github.com/moderntribe/square-one/blob/b73599614d5f8bd7fca4e6b610f9acf80feda13c/docs/concepts/templating.md) still refers to using twig and does not match the component structure that's being used and documented in [docs/concepts/components.md](https://github.com/moderntribe/square-one/blob/main/docs/concepts/components.md)

It took me a little while to figure out why those docs didn't match.

**Comment by ryanurban** [comment]
Nice, this would be a great PR to submit if you are so inclined 😃
