### ISSUE TITLE
Improve filter on nav menu classes

### ISSUE THREAD

**Issue by crstauf** [moderntribe/square-one#880]
(Sorry if this should be a discussion first.)

Because menus can be loaded via the `menu` (menu ID, slug, name, or object) parameter of `wp_nav_menu()`, this function should be adjusted:

1. if the classes are relevant only for menus includes via `theme_location`, check if `theme_location` is populated before adding classes
1. adjust to support menus included via `menu` parameter and not `theme_location`

Happy to submit a PR once a decision is made.

https://github.com/moderntribe/square-one/blob/6ae17da9de0fc3f64e37e370b651d3efc2eadbc3/wp-content/plugins/core/src/Nav_Menus/Nav_Attribute_Filters.php#L44-L85

**Comment by nickpelton** [comment]
Hey @crstauf This looks like a worthy change. We typically start with a PR rather than issues, as we track most tasks in Jira. I'm going to close this, looking forward to reviewing the PR.

**Comment by crstauf** [comment]
@nickpelton Which option should I proceed with: 1 or 2?

**Comment by crstauf** [comment]
Discussed in Slack: supporting adding classes for both `theme_location` and `menu` parameters.
