### ISSUE TITLE
Missing base CLI classes for TribeLibs integration and generator

### ISSUE THREAD

**Issue by nickpelton** [moderntribe/square-one#913]
When attempting to create a CLI command using the `wp sq1 generate cli <command name>` I got a few errors about missing files which made me realize we don't have the base classes anymore. Not sure how they were removed, logging this ticket so whomever has time can re-add them.

# Issue:
* Run `wp s1 generate cli <command name>` and see the errors generated

# Solution:
* Re-add the base definer and subscriber to the core plugin.

**Comment by defunctl** [comment]
Note the proper command to generate a CLI command is: `so wp s1 generate cli <command name>`

**Comment by nickpelton** [comment]
Updated command as I mistyped from memory.

**Comment by defunctl** [comment]
Fixed with https://github.com/moderntribe/square-one/pull/914
